import {createCipheriv,createDecipheriv,randomBytes,createHash} from 'node:crypto';
export class Connection{
 constructor(store,env){this.store=store;this.key=createHash('sha256').update(env.SETTINGS_KEY||env.ADMIN_TOKEN).digest();store.db.exec('CREATE TABLE IF NOT EXISTS connection(id INTEGER PRIMARY KEY CHECK(id=1),sealed TEXT NOT NULL)');const row=store.db.prepare('SELECT sealed FROM connection WHERE id=1').get();this.value=row?this.decode(row.sealed):{account:env.IG_ACCOUNT_ID||'',username:'',token:env.IG_ACCESS_TOKEN||'',secret:env.META_APP_SECRET||'',verify:env.META_VERIFY_TOKEN||'',version:env.GRAPH_API_VERSION||'v24.0',dryRun:env.DRY_RUN!=='false'};}
 decode(sealed){try{const b=Buffer.from(sealed,'base64');const decipher=createDecipheriv('aes-256-gcm',this.key,b.subarray(0,12));decipher.setAuthTag(b.subarray(12,28));return JSON.parse(Buffer.concat([decipher.update(b.subarray(28)),decipher.final()]).toString());}catch{throw Error('Unable to decrypt connection settings. Restore SETTINGS_KEY before starting.');}}
 public(){const c=this.value;return {account:c.account,username:c.username,version:c.version,dryRun:c.dryRun,hasToken:!!c.token,hasSecret:!!c.secret,hasVerify:!!c.verify};}
 save(input){const c={...this.value};for(const k of ['account','username','version'])if(input[k]!==undefined)c[k]=String(input[k]).trim();for(const k of ['token','secret','verify']){if(typeof input[k]==='string'&&input[k].trim())c[k]=input[k].trim();}if(typeof input.dryRun!=='boolean')throw Error('接続設定の確認モードを指定してください');c.dryRun=input.dryRun;
 if(!/^\d{1,40}$/.test(c.account)||!/^@?[A-Za-z0-9._]{0,30}$/.test(c.username)||!/^v\d{1,3}\.0$/.test(c.version)||!c.token||!c.secret||!c.verify||[c.token,c.secret,c.verify].some(s=>s.length>4096))throw Error('接続設定のアカウントID・認証情報を確認してください');
 if(c.account!==this.value.account&&(!input.token?.trim()||!input.secret?.trim()||!input.verify?.trim()))throw Error('接続先を変更するときは認証情報も再入力してください');
 const iv=randomBytes(12);const cipher=createCipheriv('aes-256-gcm',this.key,iv);const encrypted=Buffer.concat([cipher.update(JSON.stringify(c)),cipher.final()]);const sealed=Buffer.concat([iv,cipher.getAuthTag(),encrypted]).toString('base64');
 this.store.db.exec('BEGIN IMMEDIATE');try{this.store.enabled(false);this.store.db.prepare("UPDATE jobs SET state='cancelled',detail='接続設定が変更されました' WHERE state='pending'").run();if(c.account!==this.value.account)this.store.db.exec('DELETE FROM campaigns');this.store.db.prepare('INSERT INTO connection VALUES(1,?) ON CONFLICT(id) DO UPDATE SET sealed=excluded.sealed').run(sealed);this.store.db.exec('COMMIT');}catch(e){this.store.db.exec('ROLLBACK');throw e;}this.value=c;return this.public();
 }
}
